// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package ch.tamedia.noname.server.grpc.endpoint.log

object LogProto {
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
        """Cglsb2cucHJvdG8SKmNoLnRhbWVkaWEubm9uYW1lLnNlcnZlci5ncnBjLmVuZHBvaW50LmxvZyImCgpMb2dSZXF1ZXN0EhgKB
  3BheWxvYWQYASABKAlSB3BheWxvYWQiJwoLTG9nUmVzcG9uc2USGAoHbWVzc2FnZRgBIAEoCVIHbWVzc2FnZTKIAQoLTG9nRW5kc
  G9pbnQSeQoEc2VuZBI2LmNoLnRhbWVkaWEubm9uYW1lLnNlcnZlci5ncnBjLmVuZHBvaW50LmxvZy5Mb2dSZXF1ZXN0GjcuY2gud
  GFtZWRpYS5ub25hbWUuc2VydmVyLmdycGMuZW5kcG9pbnQubG9nLkxvZ1Jlc3BvbnNlIgBiBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}