// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package ch.tamedia.noname.server.grpc.endpoint.log

/** The response message containing the log response
  */
@SerialVersionUID(0L)
final case class LogResponse(
                              message: String = ""
                            ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[LogResponse] with com.trueaccord.lenses.Updatable[LogResponse] {
  @transient
  private[this] var __serializedSizeCachedValue: Int = 0
  private[this] def __computeSerializedValue(): Int = {
    var __size = 0
    if (message != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, message) }
    __size
  }
  final override def serializedSize: Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }
  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
    {
      val __v = message
      if (__v != "") {
        _output__.writeString(1, __v)
      }
    };
  }
  def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): LogResponse = {
    var __message = this.message
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __message = _input__.readString()
        case tag => _input__.skipField(tag)
      }
    }
    LogResponse(
      message = __message
    )
  }
  def withMessage(__v: String): LogResponse = copy(message = __v)
  def getField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
    __field.getNumber match {
      case 1 => {
        val __t = message
        if (__t != "") __t else null
      }
    }
  }
  override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToSingleLineUnicodeString(this)
  def companion = LogResponse
}

object LogResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[LogResponse] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[LogResponse] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): LogResponse = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    LogResponse(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String]
    )
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = LogProto.javaDescriptor.getMessageTypes.get(1)
  def messageCompanionForField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = LogResponse(
  )
  implicit class LogResponseLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, LogResponse]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, LogResponse](_l) {
    def message: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.message)((c_, f_) => c_.copy(message = f_))
  }
  final val MESSAGE_FIELD_NUMBER = 1
}
